// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go

// Package mock_ingest is a generated GoMock package.
package mock_ingest

import (
	reflect "reflect"

	imap "github.com/emersion/go-imap"
	gomock "github.com/golang/mock/gomock"
	ingest "github.com/vs49688/mailpump/ingest"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// IngestMessage mocks base method.
func (m *MockClient) IngestMessage(mailbox string, msg *imap.Message, ch chan<- ingest.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestMessage", mailbox, msg, ch)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestMessage indicates an expected call of IngestMessage.
func (mr *MockClientMockRecorder) IngestMessage(mailbox, msg, ch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestMessage", reflect.TypeOf((*MockClient)(nil).IngestMessage), mailbox, msg, ch)
}
