name: check
on:
  push:
  pull_request:
jobs:
  run-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage:
          - dep
          - fmt
          - goimports
          - gosec
          - build
          - vet
          - race
          - test
          - vuln
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --ignore-environment --keep HOME --command "./run_checks.sh ${{matrix.stage}}"
      - run: |
          git status --porcelain
          if [[ $(git status --porcelain) -ne 0 ]]; then
            exit 1
          fi

  build:
    needs:
      - run-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: vs49688-nix-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: |
          nix build .#ci
      - name: Work around https://github.com/actions/upload-artifact/issues/92
        run: |
          mkdir dist
          cp -Rp result/* dist/

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist/*
