name: check
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: vs49688-nix-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: |
          nix build .#ci
      - name: Work around https://github.com/actions/upload-artifact/issues/92
        run: |
          mkdir dist
          cp -Rp result/* dist/

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist/*
